apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: tharikashree/imageclient
          ports:
            - containerPort: 3000
          env:  
            - name: REACT_APP_API_URL
              value: "http://localhost:8000"
